# Code generated by font_to_py.py.
# Font: FreeSansBold.ttf
# Cmd: font_to_py.py FreeSansBold.ttf 96 FreeSansBold_96px.py -x
version = '0.42'

def height():
    return 96

def baseline():
    return 75

def max_width():
    return 96

def hmap():
    return True

def reverse():
    return False

def monospaced():
    return False

def min_ch():
    return 32

def max_ch():
    return 126

